service: aws-nodejs
provider:
  name: aws
  runtime: nodejs10.x
functions:
  eventCategory:
    handler: handler.eventCategory
    environment:
      STORE_HASH: { { BC_STORE_HASH } }
      BC_CLIENT: { { BC_CLIENT_ID } }
      BC_TOKEN: { { BC_CLIENT_SECRET } }
    events:
      - http:
          path: eventCategory
          method: post
          cors: true
